name: Daily Tweet Snapshots (Nitter)

on:
  schedule:
    - cron: '0 6 * * *'  # runs daily at 6AM UTC
    - cron: '0 18 * * *' # runs daily at 6PM UTC
  workflow_dispatch:     # allows manual trigger

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Shallow clone for faster checkout

      # Add caching for dependencies
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Feedparser
        run: pip install feedparser

      - name: Fetch tweet links from Nitter RSS
        run: python scripts/fetch_from_nitter.py
        continue-on-error: false # Fail if tweet fetching fails

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # New step to install Puppeteer with Chrome
      - name: Install Puppeteer with Chrome
        run: |
          npm init -y
          npm install puppeteer@21.3.8
          
          # Verify chrome installation
          node -e "console.log('Chrome executable path:', require('puppeteer').executablePath())"
          
          # Create today's date folder in screenshots directory
          TODAY=$(date -u +"%Y%m%d")
          mkdir -p screenshots/$TODAY

      # Export date as an environment variable
      - name: Set date environment variable
        run: echo "SNAPSHOT_DATE=$(date -u +"%Y%m%d")" >> $GITHUB_ENV

      - name: Screenshot Tweets
        run: node scripts/screenshot_tweets.js
        timeout-minutes: 15  # Prevent hanging runs

      - name: Check if screenshots were created
        run: |
          TODAY=$(date -u +"%Y%m%d")
          SCREENSHOT_DIR="screenshots/$TODAY"
          
          if [ -d "$SCREENSHOT_DIR" ]; then
            echo "Screenshot directory exists: $SCREENSHOT_DIR"
            ls -la "$SCREENSHOT_DIR"
            COUNT=$(ls -1 "$SCREENSHOT_DIR" | wc -l)
            echo "Found $COUNT files in screenshot directory"
          else
            echo "Warning: Screenshot directory does not exist"
          fi

      - name: Commit and Push Results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "bot@users.noreply.github.com"
          git add screenshots/
          git add public/community_feed/
          git commit -m "🖼️ Daily tweet screenshots (Nitter RSS) $(date -u +"%Y-%m-%d %H:%M UTC")" || echo "No changes to commit"
          git push
        continue-on-error: true

      # Add error notification (optional)
      - name: Notify on Failure
        if: failure()
        run: echo "Tweet snapshot workflow failed. Check logs for details."
        # You could add actual notification here, e.g. sending an email or webhook
